export const BOOKS = [
  {
    PathName: "01_genesis.htm",
    FullName: "Genesisy",
    ShortName: "Gen",
    ChapterQty: 50,
  },
  {
    PathName: "02_exodus.htm",
    FullName: "Eksodosy",
    ShortName: "Eks",
    ChapterQty: 40,
  },
  {
    PathName: "03_leviticus.htm",
    FullName: "Levitikosy",
    ShortName: "Lev",
    ChapterQty: 27,
  },
  {
    PathName: "04_numbers.htm",
    FullName: "Nomery",
    ShortName: "Nom",
    ChapterQty: 36,
  },
  {
    PathName: "05_deuteronomy.htm",
    FullName: "Deotoronomia",
    ShortName: "Deo",
    ChapterQty: 34,
  },
  {
    PathName: "06_joshua.htm",
    FullName: "Josoa",
    ShortName: "Jos",
    ChapterQty: 24,
  },
  {
    PathName: "07_judges.htm",
    FullName: "Mpitsara",
    ShortName: "Mpi",
    ChapterQty: 21,
  },
  {
    PathName: "08_ruth.htm",
    FullName: "Rota",
    ShortName: "Rot",
    ChapterQty: 4,
  },
  {
    PathName: "09_1samuel.htm",
    FullName: "1 Samoela",
    ShortName: "1Sa",
    ChapterQty: 31,
  },
  {
    PathName: "10_2samuel.htm",
    FullName: "2 Samoela",
    ShortName: "2Sa",
    ChapterQty: 24,
  },
  {
    PathName: "11_1kings.htm",
    FullName: "1 Mpanjaka",
    ShortName: "1Mp",
    ChapterQty: 22,
  },
  {
    PathName: "12_2kings.htm",
    FullName: "2 Mpanjaka",
    ShortName: "2Mp",
    ChapterQty: 25,
  },
  {
    PathName: "13_1chronicles.htm",
    FullName: "1 Tantara",
    ShortName: "1Ta",
    ChapterQty: 29,
  },
  {
    PathName: "14_2chronicles.htm",
    FullName: "2 Tantara",
    ShortName: "2Ta",
    ChapterQty: 36,
  },
  {
    PathName: "15_ezra.htm",
    FullName: "Ezra",
    ShortName: "Ezr",
    ChapterQty: 10,
  },
  {
    PathName: "16_nehemiah.htm",
    FullName: "Nehemia",
    ShortName: "Neh",
    ChapterQty: 13,
  },
  {
    PathName: "17_esther.htm",
    FullName: "Estera",
    ShortName: "Est",
    ChapterQty: 10,
  },
  {
    PathName: "18_job.htm",
    FullName: "Joba",
    ShortName: "Job",
    ChapterQty: 42,
  },
  {
    PathName: "19_psalms.htm",
    FullName: "Salamo",
    ShortName: "Slm",
    ChapterQty: 151,
  },
  {
    PathName: "20_proverbs.htm",
    FullName: "Ohabolana",
    ShortName: "Ohab",
    ChapterQty: 31,
  },
  {
    PathName: "21_ecclesiastes.htm",
    FullName: "Mpitoriteny",
    ShortName: "Mpit",
    ChapterQty: 12,
  },
  {
    PathName: "22_songofsolomon.htm",
    FullName: "Tonon-kiran’i Solomona",
    ShortName: "Ton",
    ChapterQty: 8,
  },
  {
    PathName: "23_isaiah.htm",
    FullName: "Isaia",
    ShortName: "Isa",
    ChapterQty: 66,
  },
  {
    PathName: "24_jeremiah.htm",
    FullName: "Jeremia",
    ShortName: "Jer",
    ChapterQty: 52,
  },
  {
    PathName: "25_lamentations.htm",
    FullName: "Fitomaniana",
    ShortName: "Fit",
    ChapterQty: 5,
  },
  {
    PathName: "26_ezekiel.htm",
    FullName: "Ezekiela",
    ShortName: "Ezek",
    ChapterQty: 48,
  },
  {
    PathName: "27_daniel.htm",
    FullName: "Daniela",
    ShortName: "Dan",
    ChapterQty: 14,
  },
  {
    PathName: "28_hosea.htm",
    FullName: "Hosea",
    ShortName: "Hos",
    ChapterQty: 14,
  },
  {
    PathName: "29_joel.htm",
    FullName: "Joela",
    ShortName: "Joel",
    ChapterQty: 3,
  },
  {
    PathName: "30_amos.htm",
    FullName: "Amosa",
    ShortName: "Amos",
    ChapterQty: 9,
  },
  {
    PathName: "31_obadiah.htm",
    FullName: "Obadia",
    ShortName: "Obad",
    ChapterQty: 1,
  },
  {
    PathName: "32_jonah.htm",
    FullName: "Jona",
    ShortName: "Jona",
    ChapterQty: 4,
  },
  {
    PathName: "33_micah.htm",
    FullName: "Mika",
    ShortName: "Mika",
    ChapterQty: 7,
  },
  {
    PathName: "34_nahum.htm",
    FullName: "Nahoma",
    ShortName: "Nah",
    ChapterQty: 3,
  },
  {
    PathName: "35_habakkuk.htm",
    FullName: "Habakoka",
    ShortName: "Hab",
    ChapterQty: 3,
  },
  {
    PathName: "36_zephaniah.htm",
    FullName: "Zefania",
    ShortName: "Zef",
    ChapterQty: 3,
  },
  {
    PathName: "37_haggai.htm",
    FullName: "Hagay",
    ShortName: "Hag",
    ChapterQty: 2,
  },
  {
    PathName: "38_zechariah.htm",
    FullName: "Zakaria",
    ShortName: "Zak",
    ChapterQty: 14,
  },
  {
    PathName: "39_malachi.htm",
    FullName: "Malakia",
    ShortName: "Mal",
    ChapterQty: 4,
  },
  {
    PathName: "40_matthew.htm",
    FullName: "Evanjelin’i Matio",
    ShortName: "Mat",
    ChapterQty: 28,
  },
  {
    PathName: "41_mark.htm",
    FullName: "Evanjelin’i Marka",
    ShortName: "Mark",
    ChapterQty: 16,
  },
  {
    PathName: "42_luke.htm",
    FullName: "Evanjelin’i Lioka",
    ShortName: "Liok",
    ChapterQty: 24,
  },
  {
    PathName: "43_john.htm",
    FullName: "Evanjelin’i Joany",
    ShortName: "Joan",
    ChapterQty: 21,
  },
  {
    PathName: "44_acts.htm",
    FullName: "Asan’ny Apostoly",
    ShortName: "Asan",
    ChapterQty: 28,
  },
  {
    PathName: "52_romans.htm",
    FullName: "Epistolan’i Paoly ho an’ny Romana",
    ShortName: "Rom",
    ChapterQty: 16,
  },
  {
    PathName: "53_1corinthians.htm",
    FullName: "Epistola voalohan’i Paoly ho an’ny Korintiana",
    ShortName: "1Kor",
    ChapterQty: 16,
  },
  {
    PathName: "54_2corinthians.htm",
    FullName: "Epistola faharoan’i Paoly ho an’ny Korintiana",
    ShortName: "2Kor",
    ChapterQty: 13,
  },
  {
    PathName: "55_galatians.htm",
    FullName: "Epistolan’i Paoly ho an’ny Galatiana",
    ShortName: "Gal",
    ChapterQty: 6,
  },
  {
    PathName: "56_ephesians.htm",
    FullName: "Epistolan’i Paoly ho an’ny Efeziana",
    ShortName: "Efez",
    ChapterQty: 6,
  },
  {
    PathName: "57_philippians.htm",
    FullName: "Epistolan’i Paoly ho an’ny Filipiana",
    ShortName: "Fil",
    ChapterQty: 4,
  },
  {
    PathName: "58_colossians.htm",
    FullName: "Epistolan’i Paoly ho an’ny Kolosiana",
    ShortName: "Kol",
    ChapterQty: 4,
  },
  {
    PathName: "59_1thessalonians.htm",
    FullName: "Epistola voalohan’i Paoly ho an’ny Tesalonisiana",
    ShortName: "1Tes",
    ChapterQty: 5,
  },
  {
    PathName: "60_2thessalonians.htm",
    FullName: "Epistola faharoan’i Paoly ho an’ny Tesalonisiana",
    ShortName: "2Tes",
    ChapterQty: 3,
  },
  {
    PathName: "61_1timothy.htm",
    FullName: "Epistola voalohan’i Paoly ho an’i Timote",
    ShortName: "1Tim",
    ChapterQty: 6,
  },
  {
    PathName: "62_2timothy.htm",
    FullName: "Epistola faharoan’i Paoly ho an’i Timote",
    ShortName: "2Tim",
    ChapterQty: 4,
  },
  {
    PathName: "63_titus.htm",
    FullName: "Epistolan’i Paoly ho an’i Tito",
    ShortName: "Tito",
    ChapterQty: 3,
  },
  {
    PathName: "64_philemon.htm",
    FullName: "Epistolan’i Paoly ho an’i Filemona",
    ShortName: "Flm",
    ChapterQty: 1,
  },
  {
    PathName: "65_hebrews.htm",
    FullName: "Epistolan’i Paoly ho an’ny Hebreo",
    ShortName: "Hebr",
    ChapterQty: 13,
  },
  {
    PathName: "45_james.htm",
    FullName: "Epistola Jakoba",
    ShortName: "Jak",
    ChapterQty: 5,
  },
  {
    PathName: "46_1peter.htm",
    FullName: "Epistola voalohan’i Piera",
    ShortName: "1Pie",
    ChapterQty: 5,
  },
  {
    PathName: "47_2peter.htm",
    FullName: "Epistola faharoan’i Piera",
    ShortName: "2Pie",
    ChapterQty: 3,
  },
  {
    PathName: "48_1john.htm",
    FullName: "Epistola voalohan’i Joany",
    ShortName: "1Jo",
    ChapterQty: 5,
  },
  {
    PathName: "49_2john.htm",
    FullName: "Epistola faharoan’i Joany",
    ShortName: "2Jo",
    ChapterQty: 1,
  },
  {
    PathName: "50_3john.htm",
    FullName: "Epistola fahatelon’i Joany",
    ShortName: "3Jo",
    ChapterQty: 1,
  },
  {
    PathName: "51_jude.htm",
    FullName: "Epistola Joda",
    ShortName: "Joda",
    ChapterQty: 1,
  },
  {
    PathName: "66_revelations.htm",
    FullName: "Apokalipsa",
    ShortName: "Apok",
    ChapterQty: 22,
  },
];
